### PR TITLE
Add support for blade extension

### PR DESCRIPTION
**Pull request by jericopulvera**

### CODE REVIEW

**Review by ghost — APPROVED** [review]

**Comment by sineld** [comment]
+1

**Comment by yajra** [comment]
Up++, please merge thanks :) 

-- EDIT --
Workaround while not merged. Just edit package.json manually and include this PR.

```
code ~/.vscode/extensions/wcwhitehead.bootstrap-3-snippets-0.1.0/package.json
```

**Comment by joshbenham** [comment]
Is this ever going to get merged? Blade support would be great.

**Comment by alejandrofloresm** [comment]
Please merge 👍

**Pull request closed without merging**
